language: scala
scala:
- 2.12.15
jdk:
- openjdk8
env:
  global:
  - secure: Y/dRmbyHbSqhgGrEn3/0+KyGLHGNhvlRMiY9+xVmc7lrsqXviMWm5zc7jwxKrYE3NxM/dpSmcF5KOr5etyWQmu0AFJv/IzPIJaLm4L19lK+uw6MieiKIgGIWYdNiOnAeazJPXB48NUOFMNwB6lMhgJJeGjF2m7aFDKYbZ+/xQuG7WlJnADBRVTa/SB6orKIq/2cm75sb1ZPOwnGezMxT8UvS1uVBU1deKWxH4FQVNN1Pvz3GfLEOHxJwwEaMQ2G0FfCHdC+tEnKhiQoSlCHALSeO16f/QZ3LEv25UYRZmX0c+vfiL09D3kdcKrB2c+HSHaUVuERovGFHVDarExL/yqDL4mMuuS2HILeAQNXculhP+hOhlNZgGubKfttc8Zb8EaVNdF/TRgGXkj4eilUN6QxHOnkLEv3Go5H4ee6VvvJSQdUGlV41tNKKGBH1TIc4AN8DeuisfzGEKYu2w/uPCSIf+mV2kq3c6I+kweWIxZkTAyVg4y6xtbxBrqcAKSIZZ8J5VuQCixxBYCLPmIegddPD/3hZ/Gk4sxR5B0VcfHF8gZlC34NvjCQwPheJrJ2JEDn2WHT47CYL4TUdJl+83J+toZNXlTs2VysbT/fltqVWNpZzsqLVoqVFFkq77jqxm4KzaHFYOMTQyAmZd6Bw0B3Qs97UsVatHZSIWWeHIDY=
script:
- sbt package
